// SPDX-FileCopyrightText: 2026 chhongzh <szchzcn@gmail.com>
// SPDX-License-Identifier: MIT

package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/pkg/errors"
)

const (
	outputFile       = "stealth.min.js"
	generatorPackage = "extract-stealth-evasions"
	stealthPackage   = "puppeteer-extra-plugin-stealth"
	generatedBy      = " * Generated by: https://github.com/berstend/puppeteer-extra/tree/master/packages/extract-stealth-evasions\n"
)

var generatedOnPattern = regexp.MustCompile(`(?m)^ \* Generated on: .*\n`)

func main() {
	generatorVersion := resolvePackageVersion(generatorPackage)
	stealthVersion := resolvePackageVersion(stealthPackage)

	tempDir, err := os.MkdirTemp("", "atri-webread-stealth-")
	if err != nil {
		panic(errors.Wrap(err, "create temporary directory"))
	}
	defer func() { _ = os.RemoveAll(tempDir) }()

	command := exec.Command(
		"npm", "exec", "--yes",
		"--package="+generatorPackage+"@"+generatorVersion,
		"--package="+stealthPackage+"@"+stealthVersion,
		"--", "extract-stealth-evasions",
	)
	command.Dir = tempDir
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr
	if err := command.Run(); err != nil {
		panic(errors.Wrap(err, "generate stealth script"))
	}

	generated, err := os.ReadFile(filepath.Join(tempDir, outputFile))
	if err != nil {
		panic(errors.Wrap(err, "read generated stealth script"))
	}
	generated = generatedOnPattern.ReplaceAll(generated, nil)
	metadata := fmt.Sprintf(
		"%s * Generator package: %s@%s\n * Stealth package: %s@%s\n",
		generatedBy,
		generatorPackage,
		generatorVersion,
		stealthPackage,
		stealthVersion,
	)
	if !bytes.Contains(generated, []byte(generatedBy)) {
		panic("generated stealth script is missing the expected provenance header")
	}
	generated = bytes.Replace(generated, []byte(generatedBy), []byte(metadata), 1)

	if err := os.WriteFile(outputFile, generated, 0o644); err != nil {
		panic(errors.Wrap(err, "write generated stealth script"))
	}
}

func resolvePackageVersion(name string) string {
	command := exec.Command("npm", "view", name+"@latest", "version")
	output, err := command.CombinedOutput()
	if err != nil {
		panic(errors.Wrapf(err, "resolve %s version: %s", name, strings.TrimSpace(string(output))))
	}

	version := strings.TrimSpace(string(output))
	if version == "" {
		panic(fmt.Errorf("resolve %s version: empty version", name))
	}
	return version
}
